# Generated by Django 4.0.1 on 2023-06-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='img',
            field=models.FileField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
