# Generated by Django 4.0.1 on 2023-06-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_todo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.todo')),
            ],
        ),
    ]
